# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afcca7761b14d620570417e98cff68e87d38dcee39160fffb95a7be93d638aef117137637e365139b95b1b38335903c509d94f8564834c07fe7011900853822b

test:
  secret_key_base: 9dfdd3ca862395eda9d5a09e56fde7a88a787b52b3ab455506ecbf7e54a36849bfc36ebd8ea2fe303225b78ba16dde6a062289300b18fb7411efe812271510ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
